version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "weekly"