{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name | default (include "reports-api.fullname" .) }}
  labels:
    {{- include "reports-api.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "reports-api.serviceAccountName" . }}
---
{{ range .Values.secretStore.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "reports-api.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.secretStore.name | default (include "reports-api.fullname" $) }}
    kind: SecretStore
  target:
    name: {{ .targetSecret }}
    {{- with .template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
