on:
  workflow_call:

jobs:
  build:
    name: Build and Push to GHCR
    runs-on: spv-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/weareplanet
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          #file: Path to the Dockerfile. (default {context}/Dockerfile)
          push: true
          tags: |
            ghcr.io/weareplanet/planet-taxfree-website:latest
            ghcr.io/weareplanet/planet-taxfree-website:${{ github.sha }}
      - name: Update Image Tag Values
        run: |
              chart_dir="chart"
              new_image_tag=${{ github.sha }}
      
              # Update the values.yaml file with the new image tag
              sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"        