on:
  pull_request: 
    branches:
      - main
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{github.actor}}
  GITHUB_REPO: ${{github.repository}}
jobs:
  build:
    name: Build and Push to GHCR
    runs-on: azure-non-prod
    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/weareplanet
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build an image from Dockerfile
        run: docker build -t ghcr.io/weareplanet/cisiever:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/weareplanet/cisiever:${{ github.sha }}'
          exit-code: '1'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy.sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          github-pat: ${{ secrets.GITHUB_TOKEN}}
          scanners: 'vuln,secret,misconfig'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_DISABLE_VEX_NOTICE: true

      - name: PR comment
        if: success() || failure()
        uses: sett-and-hive/sarif-to-comment-action@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          pr-number: ${{ github.event.number }}
          sarif-file: trivy.sarif
          title: Trivy Vuln Scan Results
          dry-run: false
      - name: Archive Trivy results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: trivy-output
          path: trivy.sarif
      - name: import scan results into defectdojo
        uses: ivanamat/defectdojo-import-scan@v1
        if: success() || failure()
        with:
          token: ${{ secrets.DEFECTDOJO_APIKEY }}
          defectdojo_url: https://defectdojo.test.weareplanet.com
          file: trivy.sarif
          scan_type: SARIF
          engagement: 1

  