on:
  pull_request: 
    branches:
      - main
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{github.actor}}
  GITHUB_REPO: ${{github.repository}}
jobs:
  build:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: docker build -t ghcr.io/weareplanet/cisiever:${{ github.sha }} .
      - name: Run Trivy SBOM scanner
        uses: aquasecurity/trivy-action@0.29.0
        if: success() || failure()
        with:
            scan-type: 'fs'
            format: 'github'
            output: 'dependency-results.sbom.json'
            image-ref: '.'
            github-pat: ${{ secrets.GITHUB_TOKEN}}
            scanners: 'vuln,secret,misconfig'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TRIVY_DISABLE_VEX_NOTICE: true
  
