name: Build & Deploy

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    name: Build
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: "./.github/workflows/build.yml"
    secrets: inherit